// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBodSjwGb4-DYchnQk6pokcN1TJdi7P8',
    appId: '1:1037756557067:web:cf03cc5057de7fdbce640e',
    messagingSenderId: '1037756557067',
    projectId: 'totoeng-ba2da',
    authDomain: 'totoeng-ba2da.firebaseapp.com',
    storageBucket: 'totoeng-ba2da.firebasestorage.app',
    measurementId: 'G-17VF41WCGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWsNrx57AVMs9XTSysMo54_yTys_HWXY',
    appId: '1:1037756557067:android:ad000870196b860bce640e',
    messagingSenderId: '1037756557067',
    projectId: 'totoeng-ba2da',
    storageBucket: 'totoeng-ba2da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQ-gF8cLyuQZwJG0rOaLj0R9k192hgo0',
    appId: '1:1037756557067:ios:737725fea992ae9fce640e',
    messagingSenderId: '1037756557067',
    projectId: 'totoeng-ba2da',
    storageBucket: 'totoeng-ba2da.firebasestorage.app',
    iosBundleId: 'com.example.totoeng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQ-gF8cLyuQZwJG0rOaLj0R9k192hgo0',
    appId: '1:1037756557067:ios:737725fea992ae9fce640e',
    messagingSenderId: '1037756557067',
    projectId: 'totoeng-ba2da',
    storageBucket: 'totoeng-ba2da.firebasestorage.app',
    iosBundleId: 'com.example.totoeng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeBodSjwGb4-DYchnQk6pokcN1TJdi7P8',
    appId: '1:1037756557067:web:9b5e2f559c3f5048ce640e',
    messagingSenderId: '1037756557067',
    projectId: 'totoeng-ba2da',
    authDomain: 'totoeng-ba2da.firebaseapp.com',
    storageBucket: 'totoeng-ba2da.firebasestorage.app',
    measurementId: 'G-ERDW8THBMP',
  );
}
